#!/usr/bin/env bash
# PHASE 7 · TEST — extract the document's code snippets, emit the exact command
# that would check each one, and verify that documented symbols exist in the code.
#
#   ./Scripts/claude-workflows/07-test-claude-artifacts.sh <project> <task-id>
#   ./Scripts/claude-workflows/07-test-claude-artifacts.sh <project> <task-id> --verbose
#
# Writes 07-snippets/ · 07-commands.sh · 07-api-check.tsv · 07-test.env.
#
# ** THIS PHASE RUNS NOTHING. ** It extracts, greps, and prints. Every syntax
# check and every build is written to 07-commands.sh for YOU to run.
#
# That is a rule, not a limitation: CLAUDE.md §2.12 forbids this tooling from
# invoking a compiler or a test run. Spending minutes of your machine, and then
# acting on the result, is your call — reading and grepping is not. So the
# symbol check below is a grep, and the snippet checks are text.
#
# The symbol check is a HEURISTIC. It greps for a declaration of each symbol the
# document names in backticks. A miss means "no declaration found by grep", not
# "this symbol does not exist" — anything generated by a macro, a build plugin,
# or codegen will be reported as missing and is a false positive. Read the rows,
# do not gate on the count.
. "$(dirname "$0")/../claude-utils/_common.sh"

usage_text() { sed -n '2,10p' "$0" | sed 's/^# \{0,1\}//'; }

[ $# -ge 2 ] || usage
case "$1" in -h|--help) usage "$EX_OK" ;; esac

PROJECT="$1"; TASK_ID="$2"; shift 2
check_id "$PROJECT" "project name"; check_id "$TASK_ID" "task id"

VERBOSE=0
while [ $# -gt 0 ]; do
  case "$1" in
    --verbose|-v) VERBOSE=1; shift ;;
    -h|--help)    usage "$EX_OK" ;;
    *)            die "unknown argument: $1" "$EX_USAGE" ;;
  esac
done

FILE_ENV="$(need_artifact "$PROJECT" "$TASK_ID" 02-file.env 2)"
DIR="$(task_dir "$PROJECT" "$TASK_ID")"
TARGET="$(kv_get "$FILE_ENV" TARGET)"
[ -r "$TARGET" ] || die "cannot read target: $TARGET" "$EX_PRECOND"

ROOT="$(project_field "$PROJECT" 2)"
TEST_CMD="$(project_field "$PROJECT" 4)"
GLOB="$(project_field "$PROJECT" 5)"
[ -n "$GLOB" ] || GLOB='*'

SNIP="$DIR/07-snippets"
rm -rf "$SNIP"; mkdir -p "$SNIP" || die "cannot create $SNIP"
CMDS="$DIR/07-commands.sh"
APICHK="$DIR/07-api-check.tsv"

hdr "Phase 7 · test — $(basename "$TARGET")"

# ── 1. Extract fenced snippets ─────────────────────────────────────────────
# Each snippet keeps the line it started on in its filename, so a failure you
# find by running the emitted command maps straight back to the document.
python3 - "$TARGET" "$SNIP" <<'PY'
import sys, os, re

target, outdir = sys.argv[1], sys.argv[2]
EXT = {
    'swift': 'swift', 'bash': 'sh', 'sh': 'sh', 'shell': 'sh', 'zsh': 'sh',
    'python': 'py', 'python3': 'py', 'py': 'py',
    'json': 'json', 'yaml': 'yaml', 'yml': 'yaml',
    'javascript': 'js', 'js': 'js', 'typescript': 'ts', 'ts': 'ts',
    'ruby': 'rb', 'go': 'go', 'rust': 'rs',
}

lines = open(target, encoding='utf-8').read().split('\n')
i, n, manifest = 0, 0, []
while i < len(lines):
    m = re.match(r'^[ \t]*(```|~~~)[ \t]*([A-Za-z0-9+#-]*)', lines[i])
    if not m:
        i += 1
        continue
    marker, lang = m.group(1), m.group(2).lower()
    start = i + 1
    body, i = [], i + 1
    while i < len(lines) and not re.match(r'^[ \t]*' + re.escape(marker), lines[i]):
        body.append(lines[i])
        i += 1
    i += 1
    n += 1
    # A diff block is an illustration of a change, not runnable source.
    if lang in ('diff', 'patch'):
        manifest.append((n, start, lang or 'none', '', 'skip: diff illustration'))
        continue
    if not lang:
        manifest.append((n, start, 'none', '', 'skip: no language tag'))
        continue
    ext = EXT.get(lang)
    if not ext:
        manifest.append((n, start, lang, '', 'skip: no checker for this language'))
        continue
    name = '%02d-line%d.%s' % (n, start, ext)
    with open(os.path.join(outdir, name), 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(body).rstrip('\n') + '\n')
    manifest.append((n, start, lang, name, ''))

with open(os.path.join(outdir, 'manifest.tsv'), 'w', encoding='utf-8') as fh:
    fh.write('# n\tdoc_line\tlang\tfile\tnote\n')
    for row in manifest:
        fh.write('%d\t%d\t%s\t%s\t%s\n' % row)
PY
[ $? -eq 0 ] || die "snippet extraction failed" "$EX_ERR"

MAN="$SNIP/manifest.tsv"
N_BLOCKS=$(count_rows "$MAN")
N_CHECKABLE=$(awk -F'\t' '!/^#/ && $4 != ""' "$MAN" | wc -l | tr -d ' ')
N_SKIPPED=$((N_BLOCKS - N_CHECKABLE))

# ── 2. Emit the commands ───────────────────────────────────────────────────
{
  printf '#!/usr/bin/env bash\n'
  printf '# GENERATED by 07-test-claude-artifacts.sh — %s\n' "$(now)"
  printf '# Snippets extracted from %s\n#\n' "$TARGET"
  printf '# The pipeline did NOT run any of this (CLAUDE.md §2.12). Run it yourself:\n'
  printf '#   bash %s\n#\n' "$CMDS"
  printf '# A snippet is usually a fragment, not a compilable unit — expect "missing\n'
  printf '# main", unresolved imports, and undeclared identifiers. Read a failure before\n'
  printf '# believing it: the question is whether the SYNTAX and the API names are right.\n\n'
  printf 'set -u\ncd %s\nfail=0\n\n' "$(printf '%q' "$SNIP")"

  awk -F'\t' '!/^#/ && $4 != "" {print $3 "\t" $4 "\t" $2}' "$MAN" | \
  while IFS='	' read -r lang file docline; do
    printf '# ── snippet %s (%s, document line %s)\n' "$file" "$lang" "$docline"
    case "$lang" in
      swift)
        printf 'swiftc -parse %s || fail=$((fail+1))\n\n' "$file" ;;
      bash|sh|shell|zsh)
        printf 'bash -n %s || fail=$((fail+1))\n\n' "$file" ;;
      python|python3|py)
        printf 'python3 -m py_compile %s || fail=$((fail+1))\n\n' "$file" ;;
      json)
        printf 'python3 -m json.tool %s >/dev/null || fail=$((fail+1))\n\n' "$file" ;;
      yaml|yml)
        printf 'python3 -c "import sys,yaml;yaml.safe_load(open(sys.argv[1]))" %s || fail=$((fail+1))\n\n' "$file" ;;
      javascript|js)
        printf 'node --check %s || fail=$((fail+1))\n\n' "$file" ;;
      typescript|ts)
        printf 'npx --no-install tsc --noEmit %s || fail=$((fail+1))\n\n' "$file" ;;
      go)
        printf 'gofmt -e %s >/dev/null || fail=$((fail+1))\n\n' "$file" ;;
      rust|rs)
        printf 'rustc --edition 2021 --emit=metadata -o /dev/null %s || fail=$((fail+1))\n\n' "$file" ;;
      ruby|rb)
        printf 'ruby -c %s || fail=$((fail+1))\n\n' "$file" ;;
    esac
  done

  printf 'printf "\\n%%s snippet check(s) failed\\n" "$fail"\n'
  printf 'exit $((fail > 0))\n'
} > "$CMDS"
chmod +x "$CMDS"

# ── 3. Do the documented symbols exist? ────────────────────────────────────
printf '# symbol\tkind\tdoc_line\tsection\tstatus\tevidence\n' > "$APICHK"

# Derived from the target AS IT STANDS NOW, not from phase 3's artifact: phase 3
# audited the pre-edit document, so reusing it here would report symbols that
# phase 5 has since deleted as missing from the code.
SYMBOLS="$DIR/07-symbols.tsv"
md_symbols "$TARGET" > "$SYMBOLS"
N_SYM=0; N_MISSING=0
if [ ! -d "$ROOT" ]; then
  dim "project root is gone ($ROOT) — skipping the symbol check"
else
  # Deduplicate: a symbol named ten times needs one grep, not ten.
  awk -F'\t' '$1=="api" || $1=="component" {
    sym = $4
    sub(/\(.*$/, "", sym)                  # foo(bar:) → foo
    sub(/\..*$/, "", sym)                  # URLSession.shared → URLSession
    if (sym ~ /^[A-Za-z_][A-Za-z0-9_]*$/ && length(sym) > 2 && !seen[sym]++)
      printf "%s\t%s\t%s\t%s\n", sym, $1, $2, $3
  }' "$SYMBOLS" > "$DIR/.syms.$$"

  while IFS='	' read -r sym kind docline section; do
    [ -n "$sym" ] || continue
    N_SYM=$((N_SYM + 1))
    # Declaration forms across the languages this pipeline sees. Deliberately
    # broad: a false "found" is cheaper than a false "missing", because a
    # missing row asks you to go look and a found row asks nothing.
    HIT=$(grep -rEl --include="$GLOB" \
            --exclude-dir=.git --exclude-dir=.build --exclude-dir=node_modules \
            --exclude-dir=DerivedData --exclude-dir=dist \
            "(struct|class|enum|protocol|actor|extension|func|var|let|typealias|associatedtype|def|type|interface|const)[[:space:]]+$sym\b" \
            "$ROOT" 2>/dev/null | head -1)
    if [ -n "$HIT" ]; then
      printf '%s\t%s\t%s\t%s\tfound\t%s\n' "$sym" "$kind" "$docline" "$section" \
        "${HIT#$ROOT/}" >> "$APICHK"
    else
      printf '%s\t%s\t%s\t%s\tNOT-FOUND\t—\n' "$sym" "$kind" "$docline" "$section" >> "$APICHK"
      N_MISSING=$((N_MISSING + 1))
    fi
  done < "$DIR/.syms.$$"
  rm -f "$DIR/.syms.$$"
  N_SYM=$(count_rows "$APICHK")
  N_MISSING=$(count_match '	NOT-FOUND	' "$APICHK")
fi

ENV="$DIR/07-test.env"
: > "$ENV"
kv_set "$ENV" TESTED_AT   "$(now)"
kv_set "$ENV" CODE_BLOCKS "$N_BLOCKS"
kv_set "$ENV" CHECKABLE   "$N_CHECKABLE"
kv_set "$ENV" SKIPPED     "$N_SKIPPED"
kv_set "$ENV" SYMBOLS     "$N_SYM"
kv_set "$ENV" NOT_FOUND   "$N_MISSING"
kv_set "$ENV" COMMANDS    "$CMDS"
kv_set "$ENV" PROJECT_TEST_CMD "$TEST_CMD"
kv_set "$ENV" EXECUTED    "0"

state_set "$PROJECT" "$TASK_ID" 7 done "emitted; $N_MISSING symbols unverified"

info "code blocks   $N_BLOCKS ($N_CHECKABLE checkable, $N_SKIPPED skipped)"
info "symbols       $N_SYM checked · $N_MISSING not found by grep"

if [ "$N_SKIPPED" -gt 0 ] && [ "$VERBOSE" -eq 1 ]; then
  hdr "skipped blocks"
  awk -F'\t' '!/^#/ && $4 == "" {printf "  line %-6s %-10s %s\n", $2, $3, $5}' "$MAN"
fi

if [ "$N_MISSING" -gt 0 ]; then
  hdr "documented but not found in $ROOT"
  awk -F'\t' -v d="$DIM" -v o="$OFF" \
    '$5=="NOT-FOUND" {printf "  %-28s %s(line %s · %s)%s\n", $1, d, $3, $4, o}' \
    "$APICHK" | head -20
  [ "$N_MISSING" -gt 20 ] && dim "… $((N_MISSING - 20)) more in $APICHK"
  printf '\n'
  warn "These are grep misses, not proven absences. Macro-generated, codegen'd, or
    externally-declared symbols land here as false positives. Check a few before
    concluding the doc is stale."
fi

hdr "run these yourself — the pipeline did not"
printf '  %s# snippet syntax checks%s\n' "$DIM" "$OFF"
printf '  bash %s\n' "$CMDS"
if [ -n "$TEST_CMD" ]; then
  printf '\n  %s# the project'"'"'s own tests%s\n' "$DIM" "$OFF"
  printf '  cd %s && %s\n' "$ROOT" "$TEST_CMD"
fi
printf '\n'
dim "CLAUDE.md §2.12 — this tooling never invokes the compiler. That is why the"
dim "commands are printed instead of run."
ok "wrote 07-commands.sh · 07-api-check.tsv · 07-test.env"
dim "next: run-task.sh $PROJECT $TASK_ID 8"
