#!/usr/bin/env bash
#@kind      util
#@platform  macos
#@claude    call
#@purpose   Generate .claude/SCRIPTS.tsv from the #@ metadata header of every script; fail on any script missing one.
#@usage     register-scripts.sh [--check]
#@in        --check:flag(verify only, write nothing)
#@out       .claude/SCRIPTS.tsv:tsv(path,kind,platform,claude,purpose,usage,in,out,exit,effects)
#@exit      0=in sync 1=missing or stale metadata 2=usage
#@effects   writes .claude/SCRIPTS.tsv unless --check
# Generate the script registry from the scripts themselves.
#
#   ./Scripts/claude-utils/register-scripts.sh            # write .claude/SCRIPTS.tsv
#   ./Scripts/claude-utils/register-scripts.sh --check    # verify, write nothing
#
# The registry is DERIVED, never hand-edited. Each script carries its own contract
# in a `#@` header; this collects them. A hand-maintained registry drifts from the
# scripts it describes, and a contract that lies is worse than no contract — the
# whole point is that a caller can rely on the row WITHOUT reading the body.
#
# Fails loudly when a script has no header. A script missing from the registry is
# one Claude will never call, so silence here would quietly shrink the toolset.
#
# Header fields, all required, one per line, `#@<field><spaces><value>`:
#   kind      workflow | util | tool | lib
#   platform  macos
#   claude    call | emit-only | needs-approval | never:<reason>
#   purpose   one line, what it does
#   usage     the invocation, with every flag
#   in        inputs: positional, flags, and the artifacts it reads
#   out       outputs: files with their format, and what goes to stdout
#   exit      every exit code and what it means
#   effects   read-only | what it writes | which rule gates it
. "$(dirname "$0")/_common.sh"

usage_text() { usage_from "$0"; }

CHECK=0
while [ $# -gt 0 ]; do
  case "$1" in
    --check)   CHECK=1; shift ;;
    -h|--help) usage "$EX_OK" ;;
    *)         die "unknown argument: $1" "$EX_USAGE" ;;
  esac
done

# Resolve from THIS FILE's location, not ga_home(): GA_HOME overrides where task
# artifacts are written, and honouring it here would make the registry describe a
# directory that has no scripts in it. The scripts to register are the ones sitting
# next to this file, always.
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT" || die "cannot enter $ROOT"
OUT=".claude/SCRIPTS.tsv"
TMP="${TMPDIR:-/tmp}/ga-registry.$$"
trap 'rm -f "$TMP" "$TMP.missing"' EXIT INT TERM

FIELDS="kind platform claude purpose usage in out exit effects"

# Every executable-ish thing under Scripts/, in a stable order so the registry
# diff is meaningful rather than filesystem-ordered.
SCRIPTS=$(ls Scripts/*.sh Scripts/*.py Scripts/claude-workflows/*.sh Scripts/claude-utils/*.sh 2>/dev/null | sort)
[ -n "$SCRIPTS" ] || die "no scripts found under Scripts/" "$EX_ERR"

{
  printf '#\tGenericArch script registry — GENERATED by Scripts/claude-utils/register-scripts.sh\n'
  printf '#\tDo not hand-edit. Change the #@ header in the script, then re-run.\n'
  printf '#\t  grep -i lint .claude/SCRIPTS.tsv                 which script covers this\n'
  printf '#\t  awk -F"\\t" \x27$4!="call"\x27 .claude/SCRIPTS.tsv    what Claude must not just run\n'
  printf '#\tColumns: path\tkind\tplatform\tclaude\tpurpose\tusage\tin\tout\texit\teffects\n'
} > "$TMP"

: > "$TMP.missing"
n=0
for f in $SCRIPTS; do
  # A field's value may contain anything except a tab, which would split the row.
  row="$f"
  incomplete=''
  for field in $FIELDS; do
    v=$(sed -n "s/^#@$field[[:space:]]\{1,\}//p" "$f" | head -1 | tr '\t' ' ' | sed 's/[[:space:]]*$//')
    [ -n "$v" ] || incomplete="$incomplete $field"
    row="$row	$v"
  done
  if [ -n "$incomplete" ]; then
    printf '%s\t%s\n' "$f" "$incomplete" >> "$TMP.missing"
    continue
  fi
  printf '%s\n' "$row" >> "$TMP"
  n=$((n + 1))
done

if [ -s "$TMP.missing" ]; then
  hdr "scripts with an incomplete #@ header"
  awk -F'\t' '{printf "  %-46s missing:%s\n", $1, $2}' "$TMP.missing"
  printf '\n'
  die "$(count_rows "$TMP.missing") script(s) cannot be registered.
    Add the missing field(s) to each script's #@ header, then re-run.
    A script with no row is a script Claude will never call." "$EX_ERR"
fi

# Column count must be exactly 10, or a grep of the registry silently loses rows.
BAD=$(awk -F'\t' '!/^#/ && NF != 10 {printf "%s (%d columns)\n", $1, NF}' "$TMP")
if [ -n "$BAD" ]; then
  hdr "malformed rows"
  printf '%s\n' "$BAD" | sed 's/^/  /'
  die "a value contains a tab, or a field is empty" "$EX_ERR"
fi

if [ "$CHECK" -eq 1 ]; then
  if [ -f "$OUT" ] && cmp -s "$TMP" "$OUT"; then
    ok "registry is in sync — $n script(s)"
    exit "$EX_OK"
  fi
  hdr "registry is stale"
  if [ -f "$OUT" ]; then
    diff "$OUT" "$TMP" | head -20 | sed 's/^/  /'
  else
    info "$OUT does not exist yet"
  fi
  printf '\n'
  die "run ./Scripts/claude-utils/register-scripts.sh to regenerate" "$EX_ERR"
fi

mkdir -p .claude || die "cannot create .claude"
mv "$TMP" "$OUT" || die "cannot write $OUT"

hdr "registered $n script(s) → $OUT"
awk -F'\t' -v d="$DIM" -v o="$OFF" '!/^#/ {
  printf "  %-46s %s%-9s %s%s\n", $1, d, $2, $4, o
}' "$OUT"
printf '\n'

# The gated ones are worth naming on every run: they are what a caller most needs
# to know before reaching for a script.
GATED=$(awk -F'\t' '!/^#/ && $4 != "call" {printf "  %-46s %s\n", $1, $4}' "$OUT")
if [ -n "$GATED" ]; then
  hdr "not a plain call"
  printf '%s\n' "$GATED"
fi
printf '\n'
ok "wrote $OUT"
dim "keep it in sync: ./Scripts/claude-utils/register-scripts.sh --check"
