#!/usr/bin/env bash
#@kind      tool
#@platform  macos
#@claude    call
#@purpose   Project this repo's own architecture rules into an OpenSpec config fragment, and report what OpenSpec knows that the notes do not. Computes and verifies; writes nothing.
#@usage     openspec-sync.sh [target-dir] [--check] [--tsv]
#@in        target:dir(default .) --check:flag(compare the installed span against a fresh one) --tsv:flag(machine-readable rows)
#@out       stdout:a ready-to-merge YAML fragment for openspec/config.yaml, then FEATURE/GAP/FINDING candidate rows
#@exit      0=fresh, or report produced 1=drift found under --check 2=usage 7=no openspec/config.yaml — run /openspec-install first
#@effects   read-only; runs the openspec CLI read-only when present, never the network
#@when      wire openspec to genericarch|project the rules into openspec|is the openspec context stale|what does openspec know that the notes do not|after openspec update
#
# The deterministic half of /openspec-install. Two directions, neither of which writes:
#
#   forward — read THIS repo's CLAUDE.md §2, docs/DECISIONS.md and the detected toolchain, and
#             emit the YAML fragment that carries them into OpenSpec's documented injection point.
#   reverse — ask the openspec CLI what it holds, and emit candidate rows for the notes and gaps
#             that do not know about it yet.
#
# It reads the repo it RUNS IN, never a GenericArch checkout. In an adopted repo the authoritative
# rules are partly the product's own (docs/ADOPTION.md Path A reconciles them), and CLAUDE.md does
# not travel — so a projector reading the base would arrive with its inputs missing.
#
# It does not edit openspec/config.yaml. The file is a YAML block scalar whose indentation is
# semantic, and sed/awk surgery on one is the least safe part of this integration; the command
# merges the fragment with an editor instead. Same split as sync-notes.sh and /sync-app-notes:
# the script gathers, the command applies.
set -o pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=Scripts/ga-lifecycle.sh
. "$HERE/ga-lifecycle.sh"

GA_EX_NOCONFIG=7

# Marks the span this script owns inside the `context:` scalar. It sits INSIDE the scalar, so it is
# literal text the agent reads rather than a YAML comment — the cost of leaving the consumer's own
# context intact instead of owning the whole key.
MARK_OPEN="# >>> GenericArch (generated by Scripts/openspec-sync.sh — do not edit) >>>"
MARK_CLOSE="# <<< GenericArch <<<"

UPSTREAM="https://github.com/Fission-AI/openspec"

TARGET="."; CHECK=0; TSV=0
while [ $# -gt 0 ]; do
  case "$1" in
    --check)   CHECK=1; shift ;;
    --tsv)     TSV=1; shift ;;
    -h|--help) sed -n '2,12p' "$0"; exit "$GA_EX_OK" ;;
    -*)        ga_die "unknown option: $1" "$GA_EX_USAGE" ;;
    *)         TARGET="$1"; shift ;;
  esac
done
[ -d "$TARGET" ] || ga_die "no such directory: $TARGET" "$GA_EX_USAGE"
TARGET="$(cd "$TARGET" && pwd)"
cd "$TARGET" || exit "$GA_EX_ERR"

CONFIG="openspec/config.yaml"
[ -f "$CONFIG" ] || CONFIG="openspec/config.yml"
if [ ! -f "$CONFIG" ]; then
  ga_die "no openspec/config.yaml in $TARGET — run /openspec-install first ($UPSTREAM)" "$GA_EX_NOCONFIG"
fi

TMP_CUR="$(mktemp -t ga-os-cur)"; TMP_NEW="$(mktemp -t ga-os-new)"
trap 'rm -f "$TMP_CUR" "$TMP_NEW"' EXIT INT TERM

say() { [ "$TSV" -eq 1 ] || printf '%s\n' "$1"; }
hdr() { [ "$TSV" -eq 1 ] || ga_hdr "$1"; }
row() { [ "$TSV" -eq 1 ] && printf '%s\t%s\t%s\n' "$1" "$2" "$3"; }

# ── Forward: what this repo knows ──────────────────────────────────────────

# The §2 rule headlines, and nothing else from the section. The bold clause is the rule; the prose
# after it is elaboration that costs a re-send on every artifact command. The §N number is kept
# deliberately — it is how an agent gets from the headline back to the full text, and ~380 places
# in this repo cite rules that way.
# CLAUDE.md is not always at the install root. An Xcode project often sits in a subdirectory of its
# checkout and the rules file goes beside it — Scripts/find.sh makes the same allowance for
# .claude/notes/, and a real install found this way round: root `.claude/`, rules one level down.
# Assuming the root silently projected ZERO rules, which is worse than failing, so: prefer the root,
# otherwise take the shallowest and name it. §2.16 component files sit deeper and lose the sort.
claude_md() {
  if [ -f CLAUDE.md ]; then printf 'CLAUDE.md\n'; return 0; fi
  find . -maxdepth 3 -name CLAUDE.md -not -path './.build/*' -not -path './.git/*' 2>/dev/null \
    | sed 's|^\./||' \
    | awk -F/ '{ print NF"\t" $0 }' \
    | LC_ALL=C sort -n -k1,1 -k2,2 \
    | head -1 | cut -f2-
}

rules_headlines() {
  _cm="$(claude_md)"
  [ -n "$_cm" ] && [ -f "$_cm" ] || return 0
  # Key on the SHAPE of a rule, not on a section number. An adopted repo's CLAUDE.md is reconciled
  # by /project-init and does not keep this base's numbering — a real one carried its rules under
  # `## Rules`, with no `## 2.` anywhere, so anchoring on the number projected nothing at all.
  #
  # So: take numbered bold list items wherever they appear, and cite them by the heading they sit
  # under. `## 2. …` still yields §2.N, which is what ~380 references in THIS repo expect; any other
  # heading yields its own name, which is what an adopted repo can actually be pointed back to.
  awk '
    /^#+ / {
      head = $0
      sub(/^#+ +/, "", head)
      sec = (head ~ /^2\./) ? "§2" : head
      next
    }
    /^[0-9]+\. \*\*/ {
      num = substr($0, 1, index($0, ".") - 1)
      line = $0
      sub(/^[0-9]+\. \*\*/, "", line)
      sub(/\*\*.*$/, "", line)
      if (sec == "§2") printf "  §2.%s %s\n", num, line
      else if (sec != "")   printf "  %s %s: %s\n", sec, num, line
      else                  printf "  %s. %s\n", num, line
    }
  ' "$_cm"
}

# The rejected options, collapsed to one line. Cheap, and it prevents the most expensive failure an
# OpenSpec agent can have here: proposing something this repo already argued down.
rejected_oneline() {
  [ -f docs/DECISIONS.md ] || return 0
  awk -F'|' '
    /^## Do not re-propose/ { inx = 1; next }
    inx && /^## /           { exit }
    inx && /^\|/ && $0 !~ /^\|[- ]*-/ && $2 !~ /Rejected/ {
      item = $2
      gsub(/^ +| +$/, "", item)
      # Order matters: drop the trailing italic parenthetical first, then the code and bold
      # markers. Stripping every asterisk up front would eat the glob in `docs/modules/*.md`.
      sub(/ *\*\([^)]*\)\* *$/, "", item)
      gsub(/`/, "", item)
      gsub(/\*\*/, "", item)
      gsub(/ +$/, "", item)
      out = out (out ? " · " : "") item
    }
    END { if (out) print "  Already rejected — do not re-propose: " out }
  ' docs/DECISIONS.md
}

# The §0 questions, which an OpenSpec proposal must name rather than assume. Taken from the prose
# list under the heading, so the two cannot drift apart.
ask_every_time() {
  [ -f docs/DECISIONS.md ] || return 0
  # The list is prose that wraps across several lines and closes with a full stop; the lines after
  # it are elaboration this projection does not need. So accumulate from the first line carrying a
  # separator until the sentence ends, and stop there.
  awk '
    /^## Ask every time/ { inx = 1; next }
    inx && /^## /        { exit }
    inx && !done && (/·/ || line != "") {
      line = line (line ? " " : "") $0
      if ($0 ~ /\.[ ]*$/) done = 1
    }
    END {
      if (line) {
        gsub(/\[([^]]*)\]\([^)]*\)/, "\\1", line)
        gsub(/`/, "", line)
        gsub(/\*\*/, "", line)
        gsub(/^ +| +$/, "", line)
        print "  Must be asked, never assumed: " line
      }
    }
  ' docs/DECISIONS.md
}

# The resolved stack, from the detector rather than from .claude/notes/PROJECT.md. PROJECT.md is a
# recorded copy that docs/DECISIONS.md already reports as having named targets a repo did not have;
# prepending a wrong value here would turn a grep-time mistake into an always-on one.
stack_values() {
  [ -x ./Scripts/detect-toolchain.sh ] || return 0
  ./Scripts/detect-toolchain.sh --markdown 2>/dev/null | awk -F'|' '
    /^\| / && $0 !~ /^\|[- ]*-/ && $2 !~ /Item/ {
      k = $2; v = $3
      gsub(/^ +| +$/, "", k); gsub(/^ +| +$/, "", v); gsub(/\*/, "", v)
      if (v != "unset") printf "  %s: %s\n", k, v
    }
  '
}

projection() {
  _r="$(rules_headlines)"; _s="$(stack_values)"
  _x="$(rejected_oneline)"; _a="$(ask_every_time)"
  _cm="$(claude_md)"
  # Cite the rules file the way the rules were actually labelled. Saying "§2" over a reconciled
  # CLAUDE.md that has no §2 sends the reader looking for a section that is not there.
  case "$_r" in
    *"§2."*) _cite="${_cm:-CLAUDE.md} §2" ;;
    *)       _cite="${_cm:-CLAUDE.md}" ;;
  esac
  printf '  %s\n' "$MARK_OPEN"
  echo "  This repo's architecture rules. Full text and rationale: $_cite,"
  echo "  docs/DECISIONS.md, docs/DONE.md. Route a lookup with .claude/MAP.tsv or ./Scripts/find.sh."
  # Only claim a section that has content. An earlier version printed the heading unconditionally,
  # so a repo whose rules file was not where it looked emitted "Rules that must never be broken:"
  # followed by nothing — which reads as "there are none", the opposite of the truth.
  if [ -n "$_r" ]; then
    echo "  Rules that must never be broken:"
    printf '%s\n' "$_r"
  fi
  [ -n "$_s" ] && printf '%s\n' "$_s"
  [ -n "$_x" ] && printf '%s\n' "$_x"
  [ -n "$_a" ] && printf '%s\n' "$_a"
  printf '  %s\n' "$MARK_CLOSE"
}

# True when the projection would carry nothing an agent could act on. Two boilerplate lines and a
# pair of markers is not memory; injecting it costs tokens on every artifact command and buys a
# claim that this repo has no rules.
projection_is_empty() {
  [ -z "$(rules_headlines)$(rejected_oneline)$(ask_every_time)" ]
}

# The span as it currently sits in the config. Indentation belongs to the YAML scalar, not to us,
# so it is normalised away on both sides before comparison — a re-indent is not drift.
installed_span() {
  # `close` is a built-in awk function name and cannot be a variable, hence the prefixes.
  awk -v mopen="$MARK_OPEN" -v mclose="$MARK_CLOSE" '
    index($0, mopen)         { inx = 1 }
    inx                      { print }
    inx && index($0, mclose) { exit }
  ' "$CONFIG"
}

undent() { sed 's/^[[:space:]]*//'; }

# ── Reverse: what OpenSpec knows ───────────────────────────────────────────
#
# Read their documented JSON CLI, never their markdown. The CLI is a stated interface with stable
# flags; the spec format is prose they revise. Parse with node, which is already a hard prerequisite
# for the CLI itself — so this adds no dependency, and does not need jq.
os_json() {  # os_json <subcommand...> ; prints JSON on success, nothing on any failure
  command -v openspec >/dev/null 2>&1 || return 1
  openspec "$@" --json 2>/dev/null || return 1
}

# An interface we cannot read is a defect in THIS repo, not a fact about the user's day. So the
# report ends with the command that turns it into tracked work rather than a line someone scrolls
# past.
#
# An ISSUE, and nothing else. No branch, no commit, no PR — filing an issue touches no history, so
# §2.11 is not in play here and needs no exception. The fix itself is ordinary work afterwards.
#
# Printed, never run: this script is read-only by contract (#@effects), and opening an issue posts
# to a public tracker. /openspec-install may run it after showing you the text.
GA_ISSUES="https://github.com/kalpesh-jetani/GenericArch/issues"

# Single-quote for the shell: ' becomes '\'' so the printed command survives a copy-paste. Both
# arguments routinely contain a quoted CLI invocation, and an unescaped one closes the outer quote
# early — which is how a "ready to run" command turns into a syntax error at the worst moment.
_sq() { printf "%s" "$1" | sed "s/'/'\\\\''/g"; }

file_it() {  # file_it <what-broke> <the-command-or-path>
  _br="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
  _title="$(_sq "openspec-sync: $1")"
  _body="$(_sq "Detected by ./Scripts/openspec-sync.sh on branch $_br, against: $2. Upstream: $UPSTREAM — re-check the CLI reference and update the parser.")"
  say ""
  say "  ${GA_BLD}This is a defect here — revise this script, and file it:${GA_OFF}"
  say "    gh issue create --repo kalpesh-jetani/GenericArch \\"
  say "      --title '$_title' \\"
  say "      --body '$_body'"
  say "    ${GA_DIM}issues: $GA_ISSUES${GA_OFF}"
}

node_pick() {  # node_pick <expression over the parsed object as `d`>
  command -v node >/dev/null 2>&1 || return 1
  node -e '
    let raw = ""
    process.stdin.on("data", c => raw += c)
    process.stdin.on("end", () => {
      let d
      try { d = JSON.parse(raw) } catch { process.exit(3) }
      try { process.stdout.write(String(eval(process.argv[1]) ?? "")) }
      catch { process.exit(3) }
    })
  ' "$1" 2>/dev/null || return 1
}

reverse_pass() {
  if ! command -v openspec >/dev/null 2>&1; then
    say "  ${GA_DIM}UPSTREAM-UNAVAILABLE — the openspec CLI is not on PATH. $UPSTREAM${GA_OFF}"
    row UPSTREAM-UNAVAILABLE "openspec" "not on PATH"
    return 0
  fi
  if ! command -v node >/dev/null 2>&1; then
    say "  ${GA_DIM}UPSTREAM-UNAVAILABLE — node is required to read the CLI's JSON${GA_OFF}"
    row UPSTREAM-UNAVAILABLE "node" "not on PATH"
    return 0
  fi

  changes="$(os_json list)" || changes=""
  if [ -z "$changes" ]; then
    # The CLI is present and still gave us nothing, so a flag or subcommand has most likely moved.
    # A missing CLI is the user's situation; this is ours.
    say "  ${GA_YEL}UPSTREAM-UNAVAILABLE${GA_OFF} — the CLI is installed but 'openspec list --json'"
    say "  ${GA_DIM}produced nothing. A flag or subcommand has probably moved.${GA_OFF}"
    row UPSTREAM-UNAVAILABLE "openspec list --json" "no output from an installed CLI"
    file_it "'openspec list --json' produced no output" "openspec list --json"
    return 0
  fi

  # Their JSON shape is theirs to change. A shape we cannot read is reported, never guessed at — a
  # wrong FEATURES.md row is worse than a missing one, because it looks current.
  names="$(printf '%s' "$changes" | node_pick '
    (Array.isArray(d) ? d : d.changes || d.items || [])
      .map(c => typeof c === "string" ? c : (c.id || c.name || ""))
      .filter(Boolean).join("\n")
  ')" || names=""
  if [ -z "$names" ] && [ "$(printf '%s' "$changes" | tr -d '[:space:]')" != "[]" ]; then
    say "  ${GA_YEL}SHAPE-UNRECOGNISED${GA_OFF} — 'openspec list --json' returned a shape this script"
    say "  ${GA_DIM}does not know. Re-check the CLI reference: $UPSTREAM${GA_OFF}"
    row SHAPE-UNRECOGNISED "openspec list --json" "unrecognised keys"
    file_it "unrecognised shape from 'openspec list --json'" "openspec list --json"
    return 0
  fi

  if [ -z "$names" ]; then
    say "  ${GA_DIM}no active changes${GA_OFF}"
    return 0
  fi

  for c in $names; do
    say "  ${GA_YEL}IN-FLIGHT${GA_OFF}   $c ${GA_DIM}— /new-feature must not scaffold over this${GA_OFF}"
    row IN-FLIGHT "$c" "active change"
    if [ -f .claude/notes/FEATURES.md ] && ! grep -qi -- "$c" .claude/notes/FEATURES.md 2>/dev/null; then
      say "  ${GA_DIM}FEATURE-ROW  $c — no row in .claude/notes/FEATURES.md${GA_OFF}"
      row FEATURE-ROW "$c" "absent from FEATURES.md"
    fi
  done

  findings="$(os_json validate --report findings)" || findings=""
  if [ -n "$findings" ]; then
    n="$(printf '%s' "$findings" | node_pick '
      (Array.isArray(d) ? d : d.findings || d.items || []).length
    ')" || n=""
    case "$n" in
      ''|0) : ;;
      *) say "  ${GA_YEL}FINDINGS${GA_OFF}    $n from 'openspec validate --report findings'"
         row FINDINGS "$n" "upstream validation" ;;
    esac
  fi
}

# ── Report ─────────────────────────────────────────────────────────────────

fresh="$(projection)"

# Refuse to offer an empty span rather than writing one that says this repo has no rules. The usual
# cause is that the rules file is somewhere claude_md() did not look, or that /project-init has not
# recorded its answers yet — both are fixable, and neither is fixed by injecting boilerplate.
if projection_is_empty; then
  ga_warn "nothing to project in $TARGET — no §2 rules, no rejected options, no ask-list"
  say "  ${GA_DIM}looked for the rules in: ${GA_OFF}${_cm:-<none found>}"
  say "  ${GA_DIM}A repo whose rules live elsewhere, or a /project-init that has not recorded its"
  say "  answers yet, both land here. Fix the input — an empty context is pure cost.${GA_OFF}"
  row EMPTY "$TARGET" "no rules to project"
  exit "$GA_EX_ERR"
fi

if [ "$CHECK" -eq 1 ]; then
  current="$(installed_span | undent)"
  if [ -z "$current" ]; then
    ga_warn "no GenericArch span in $CONFIG — it has never been projected"
    row ABSENT "$CONFIG" "never projected"
    exit "$GA_EX_ERR"
  fi
  want="$(printf '%s\n' "$fresh" | undent)"
  if [ "$current" = "$want" ]; then
    [ "$TSV" -eq 1 ] || ga_ok "$CONFIG carries the current projection"
    row FRESH "$CONFIG" "span matches"
    exit "$GA_EX_OK"
  fi
  ga_warn "$CONFIG is stale — the span no longer matches this repo's rules"
  if [ "$TSV" -eq 0 ]; then
    printf '%s\n' "$current" > "$TMP_CUR"
    printf '%s\n' "$want"    > "$TMP_NEW"
    diff -u "$TMP_CUR" "$TMP_NEW" | sed '1,2d'
  fi
  row DRIFT "$CONFIG" "span differs"
  exit "$GA_EX_ERR"
fi

hdr "── Forward: merge this into $CONFIG ────────────────────"
say "${GA_DIM}Inside the 'context:' block scalar, indented to match it. Replace any existing span"
say "between the same two markers. Bytes: $(printf '%s' "$fresh" | wc -c | tr -d ' ').${GA_OFF}"
say ""
printf '%s\n' "$fresh"
say ""
say "${GA_DIM}Per-artifact rules and operation guidance are 'rules:' and 'operations:' keys — see"
say "docs/OPENSPEC.md for which of our rules belongs on which artifact, and $UPSTREAM for the"
say "key reference. Keyed rules are cheaper than context: they are sent only for their artifact.${GA_OFF}"

hdr "── Reverse: what OpenSpec holds that the notes do not ──"
reverse_pass

hdr "── Nothing was written ─────────────────────────────────"
say "${GA_DIM}Candidates only. /openspec-install merges the fragment and applies the rows as"
say "targeted edits, then reseals. A full note rescan is /sync-app-notes and is the user's to run.${GA_OFF}"
exit "$GA_EX_OK"
