#!/usr/bin/env bash
#@kind      tool
#@platform  macos
#@claude    call
#@purpose   Regenerate the mechanically-derivable notes offline, and gather candidate evidence for the ones that need judgement — so /sync-app-notes reviews rows instead of running scans.
#@usage     sync-notes.sh [--check|--apply|--evidence] [--init-markers] [--only NOTE] [--src DIR]
#@in        --check:flag(compare, write nothing, exit 1 on drift) --apply:flag(rewrite the managed rows) --evidence:flag(candidates for the judgement notes) --init-markers:flag(place the managed-row markers once) --only:enum(FONTS ASSETS-COLORS PROJECT) --src:dir(source root, default the repo root)
#@out       stdout:per-note table(generated,current,verdict); --apply rewrites rows between markers; --evidence writes .claude/notes/.evidence/*.tsv
#@exit      0=in sync or applied 1=drift found (--check) or a generator failed 2=usage 3=no markers yet
#@effects   --apply writes ONLY between the managed-row markers of the notes it can fully generate; --evidence writes candidate files; --check and the default write nothing
#@when      regenerate the notes|notes are stale|update fonts colours note|sync notes offline|ci check the notes|without claude|candidate rows for review
#
# Three of the nine inventories are a deterministic parse of files on disk: fonts, colours, and the
# resolved stack. Nothing about them needs a model, a network, or a judgement call — so they should
# never cost a session. This script writes those, offline, and exits non-zero in --check when they
# have drifted, which makes it a CI gate.
#
# The other six are not mechanical, and the reason is recorded: an "unused asset" list was wrong
# three times running, `grep "case "` overcounts routes 4×, and two Swift shapes hide real screens
# (docs/SCAN-TRAPS.md). For those, --evidence writes CANDIDATES with the method's blind spot
# attached, and /sync-app-notes reviews them. Reviewing a candidate list is a fraction of scanning.
#
# It never rewrites a note wholesale. Managed markers bound exactly the rows it owns; prose, rules,
# headers and hand-written rows outside them are never touched. A note with no markers is reported,
# not guessed at — run --init-markers once.
#
# When a generator fails it writes a bounded handoff report and says so, rather than emitting a
# half-built table. A partial note that looks complete is the failure this whole file exists to
# avoid.
set -o pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
SRC="$ROOT"
MODE="report"; ONLY=""; INIT=0
NOTES="$ROOT/.claude/notes"
EVID="$NOTES/.evidence"

RED=$'\033[31m'; YEL=$'\033[33m'; GRN=$'\033[32m'; DIM=$'\033[2m'; BLD=$'\033[1m'; OFF=$'\033[0m'
[ -t 1 ] || { RED=''; YEL=''; GRN=''; DIM=''; BLD=''; OFF=''; }

while [ $# -gt 0 ]; do
  case "$1" in
    --check)        MODE="check"; shift ;;
    --apply)        MODE="apply"; shift ;;
    --evidence)     MODE="evidence"; shift ;;
    --init-markers) INIT=1; shift ;;
    --only)         ONLY="${2:-}"; shift 2 || true ;;
    --src)          SRC="${2:-}"; shift 2 || true ;;
    -h|--help)      sed -n '5,8p' "$0"; exit 2 ;;
    *)              printf 'unknown option: %s\n' "$1" >&2; exit 2 ;;
  esac
done
[ -d "$SRC" ] || { printf 'no such directory: %s\n' "$SRC" >&2; exit 2; }
[ -d "$NOTES" ] || { printf 'no .claude/notes/ here — nothing to sync\n' >&2; exit 2; }

MARK_OPEN='<!-- GA:ROWS — generated by Scripts/sync-notes.sh; edits between these markers are overwritten -->'
MARK_CLOSE='<!-- GA:ROWS end -->'

fail_count=0
handoff() {   # handoff <generator> <cause> [file]
  "$HERE/ga-handoff.sh" "$1" 1 --cause "$2" ${3:+--file "$3"} >/dev/null 2>&1 || true
  printf '  %s✗%s %s — %s\n' "$RED" "$OFF" "$1" "$2" >&2
  fail_count=$((fail_count + 1))
}

# ── The generators ─────────────────────────────────────────────────────────
# Each prints the note's data rows on stdout and nothing else. A generator that cannot produce a
# COMPLETE table must exit non-zero and print nothing: a partial table that looks whole is worse
# than an empty one, because the gaps are invisible to the reader.
#
# Three exits, and the middle one matters: 0 rows produced · 3 this repo has none of that asset,
# which is a fact and not a failure · 1 the generator broke, which earns a handoff report. Conflating
# 3 with 1 files a bug report against every repo that simply ships no custom fonts.
GA_NONE=3

gen_FONTS() {
  find "$SRC" \( -name '*.ttf' -o -name '*.otf' \) -not -path '*/.git/*' -print -quit 2>/dev/null \
    | grep -q . || return "$GA_NONE"
  out="$(python3 "$HERE/scan-fonts.py" "$SRC" 2>/dev/null)" || return 1
  [ -n "$out" ] || return 1
  reg="$(grep -rl 'UIAppFonts\|ATSApplicationFontsPath' --include='*.plist' "$SRC" 2>/dev/null \
         | head -1 | sed "s|$SRC/||")"
  printf '| File | Family | PostScript name | Registered in |\n|---|---|---|---|\n'
  printf '%s\n' "$out" | while IFS="$(printf '\t')" read -r file fam ps; do
    [ -n "$file" ] || continue
    printf '| `%s` | %s | `%s` | %s |\n' "$file" "${fam#family=}" "${ps#postscript=}" "${reg:-**not registered**}"
  done
}

gen_ASSETS-COLORS() {
  find "$SRC" -type d -name '*.colorset' -not -path '*/.git/*' -print -quit 2>/dev/null \
    | grep -q . || return "$GA_NONE"
  out="$(python3 "$HERE/scan-colors.py" "$SRC" 2>/dev/null)" || return 1
  [ -n "$out" ] || return 1
  printf '| Token | Any / Light | Dark |\n|---|---|---|\n'
  printf '%s\n' "$out" | while IFS="$(printf '\t')" read -r name any dark; do
    [ -n "$name" ] || continue
    case "$dark" in -|'') dark='**one appearance only**' ;; esac
    printf '| `%s` | %s | %s |\n' "$name" "$any" "$dark"
  done
}

gen_PROJECT() {
  # detect-toolchain.sh already emits this table, and it is the only thing allowed to: a version
  # written anywhere else is a version someone will quote from memory (CLAUDE.md §1).
  out="$(cd "$SRC" && "$HERE/detect-toolchain.sh" --markdown 2>/dev/null | grep '^|')" || return 1
  [ -n "$out" ] || return 1
  printf '%s\n' "$out"
}

# ── Partially generated ────────────────────────────────────────────────────
# The middle tier, and the point of it: a note being "judgement" does not mean *every column* is.
# ASSETS-IMAGES is a deterministic inventory with one judgement column (is it unused). API-MAP has
# provable paths and unprovable screen pairing. NAVIGATION can prove which cases are DECLARED and
# only guesses at which are reachable.
#
# So the script writes what it can prove and states, inside the note, what it did not. The reviewer
# then works on a named remainder instead of re-deriving the whole table — and the note never reads
# as complete when it is not, which is the only way partial output is safe.
gen_ASSETS-IMAGES() {
  find "$SRC" -type d -name '*.imageset' -not -path '*/.git/*' -print -quit 2>/dev/null \
    | grep -q . || return "$GA_NONE"
  printf '| Asset | Catalog path | Variants | Dark appearance |\n|---|---|---|---|\n'
  find "$SRC" -type d -name '*.imageset' -not -path '*/.git/*' 2>/dev/null | LC_ALL=C sort |
  while IFS= read -r d; do
    n="$(basename "$d" .imageset)"
    v="$(find "$d" -type f \( -name '*.png' -o -name '*.pdf' -o -name '*.svg' \) 2>/dev/null | grep -c . || true)"
    dark='no'
    grep -q '"appearances"' "$d/Contents.json" 2>/dev/null && dark='yes'
    printf '| `%s` | `%s` | %s | %s |\n' "$n" "${d#"$SRC"/}" "$v" "$dark"
  done
}

gen_API-MAP() {
  json="$(python3 "$HERE/scan-api-map.py" "$SRC" 2>/dev/null)" || return 1
  printf '%s' "$json" | grep -q '"declared": 0' && return "$GA_NONE"
  printf '%s' "$json" | python3 -c '
import json, sys
d = json.load(sys.stdin)
rows = d.get("rows", [])
if not rows: sys.exit(1)
print("| Method | Path | Router | Case | Screen |")
print("|---|---|---|---|---|")
for r in sorted(rows, key=lambda r: (r.get("enum", ""), r.get("case", ""))):
    for path in (r.get("paths") or ["?"]):
        # The screen column stays explicitly unproven rather than empty: an empty cell reads as
        # "no screen", a marked one reads as "not established", and only one of those is true.
        screen = "?" if d.get("pairing") == "unproven" else                  ", ".join(sorted({c.get("screen","?") for c in r.get("callers", [])})) or "?"
        print("| %s | `%s` | `%s` | `%s` | %s |" % (
            r.get("method", "?"), path, r.get("enum", "?"), r.get("case", "?"), screen))
' || return 1
}

gen_NAVIGATION() {
  files="$(grep -rl 'enum .*Route\|enum Route\|enum .*Destination' --include='*.swift' "$SRC" 2>/dev/null)"
  [ -n "$files" ] || return "$GA_NONE"
  printf '| Route case | Declared in | Navigated to (call sites) |\n|---|---|---|\n'
  printf '%s\n' "$files" | while IFS= read -r f; do
    [ -n "$f" ] || continue
    awk '/^[[:space:]]*case[[:space:]]/ {
           line = $0; sub(/^[[:space:]]*case[[:space:]]+/, "", line); sub(/\(.*/, "", line)
           sub(/[[:space:]]*=.*/, "", line); split(line, a, ",")
           for (i in a) { gsub(/[^A-Za-z0-9_]/, "", a[i]); if (a[i] != "") print a[i] }
         }' "$f" | LC_ALL=C sort -u | while IFS= read -r c; do
      [ -n "$c" ] || continue
      # A route is a case that is navigated TO — counting declarations alone overcounts 4×
      # (docs/SCAN-TRAPS.md). The call-site count is the evidence, and 0 is a finding.
      #
      # Two shapes are NOT navigations and must not be counted. The declaration excludes
      # itself: `case placeholder` carries no dot, so the pattern never matched it — which is
      # why nothing is subtracted here. A destination switch's `case .placeholder:` MAPS the
      # route rather than navigating to it, so those lines are dropped instead. Subtracting a
      # flat 1 for it undercounted every route by one and reported a route with exactly one
      # call site as dead.
      n=$(grep -rh --include='*.swift' "\.$c\b" "$SRC" 2>/dev/null \
            | grep -v "case[[:space:]]*\.$c\b" \
            | grep -o "\.$c\b" | grep -c . || true)
      printf '| `%s` | `%s` | %s |\n' "$c" "${f#"$SRC"/}" "$([ "$n" -eq 0 ] && echo '**0 — never navigated to**' || echo "$n")"
    done
  done
}

gen_SCHEMES() {
  cfgs="$(find "$SRC" -name '*.xcconfig' -not -path '*/.git/*' 2>/dev/null | LC_ALL=C sort)"
  schemes="$(find "$SRC" -name '*.xcscheme' -not -path '*/.git/*' 2>/dev/null | LC_ALL=C sort)"
  [ -n "$cfgs$schemes" ] || return "$GA_NONE"
  printf '| Kind | Name | File |\n|---|---|---|\n'
  printf '%s\n' "$schemes" | while IFS= read -r f; do
    [ -n "$f" ] || continue
    printf '| scheme | `%s` | `%s` |\n' "$(basename "$f" .xcscheme)" "${f#"$SRC"/}"
  done
  printf '%s\n' "$cfgs" | while IFS= read -r f; do
    [ -n "$f" ] || continue
    printf '| xcconfig | `%s` | `%s` |\n' "$(basename "$f" .xcconfig)" "${f#"$SRC"/}"
  done
}

MECHANICAL="FONTS ASSETS-COLORS PROJECT"
PARTIAL="ASSETS-IMAGES API-MAP NAVIGATION SCHEMES"
# What each partial generator does NOT prove — printed into the note, so a reader never mistakes a
# generated table for a complete one.
UNPROVEN="ASSETS-IMAGES:whether an asset is USED — runtime-composed names are invisible to any scan
API-MAP:which screen calls each endpoint — no call convention was assumed
NAVIGATION:whether a case with call sites is a real destination or a coincidental name match
SCHEMES:xcconfig inheritance, per-configuration overrides, and which scheme maps to which stage"
# Why each of the rest is not here, so nobody has to re-derive it: see docs/SCAN-TRAPS.md.
JUDGEMENT="FEATURES:two Swift shapes hide real screens; what counts as a screen is a judgement
STYLE-GUIDE:which repeated value is a token and which is a one-off cannot be parsed"

# ── Marker plumbing ────────────────────────────────────────────────────────
has_markers() { grep -qF "$MARK_OPEN" "$1" 2>/dev/null; }

current_rows() {   # everything between the markers
  awk -v o="$MARK_OPEN" -v c="$MARK_CLOSE" '
    index($0, o) { inb = 1; next }
    index($0, c) { inb = 0; next }
    inb { print }
  ' "$1"
}

replace_rows() {   # replace_rows <note-file> <rows-file>
  tmp="$1.tmp"
  awk -v o="$MARK_OPEN" -v c="$MARK_CLOSE" -v rows="$2" '
    index($0, o) { print; while ((getline l < rows) > 0) print l; close(rows); inb = 1; next }
    index($0, c) { inb = 0; print; next }
    inb { next }
    { print }
  ' "$1" > "$tmp" && mv "$tmp" "$1"
}

init_markers() {   # place the markers around a note's first data table, once
  f="$1"
  has_markers "$f" && { printf '  %s·%s %-16s markers already present\n' "$DIM" "$OFF" "$(basename "$f" .md)"; return 0; }
  tmp="$f.tmp"
  # The first table in the file is the data table by convention (S9: header, then rows). The markers
  # go around it, header included, because a generator owns the columns as well as the rows.
  awk -v o="$MARK_OPEN" -v c="$MARK_CLOSE" '
    !done && /^\|/ && !intable { print o; intable = 1 }
    intable && !/^\|/ { print c; intable = 0; done = 1 }
    { print }
    END { if (intable) print c }
  ' "$f" > "$tmp" && mv "$tmp" "$f"
  has_markers "$f" \
    && printf '  %s+%s %-16s markers placed\n' "$GRN" "$OFF" "$(basename "$f" .md)" \
    || printf '  %s!%s %-16s no table found — place the markers by hand\n' "$YEL" "$OFF" "$(basename "$f" .md)"
}

# ── --init-markers ─────────────────────────────────────────────────────────
if [ "$INIT" -eq 1 ]; then
  printf '%s── Placing managed-row markers ────────────────────────%s\n' "$BLD" "$OFF"
  for n in $MECHANICAL $PARTIAL; do
    [ -n "$ONLY" ] && [ "$ONLY" != "$n" ] && continue
    [ -f "$NOTES/$n.md" ] && init_markers "$NOTES/$n.md"
  done
  printf '\n%sOne-time, and reviewable: two HTML comments per note. Then --apply owns those rows.%s\n' "$DIM" "$OFF"
  exit 0
fi

# ── --evidence ─────────────────────────────────────────────────────────────
if [ "$MODE" = "evidence" ]; then
  mkdir -p "$EVID"
  printf '%s── Evidence for the notes that need judgement ─────────%s\n\n' "$BLD" "$OFF"
  printf '%s\n%s\n' "$UNPROVEN" "$JUDGEMENT" | while IFS=: read -r note why; do
    [ -n "$note" ] || continue
    [ -n "$ONLY" ] && [ "$ONLY" != "$note" ] && continue
    f="$EVID/$note.tsv"
    {
      printf '#\tCANDIDATES for %s — not verified, not rows yet.\n' "$note"
      printf '#\tWhy this cannot be generated: %s\n' "$why"
      printf '#\tGenerated offline by Scripts/sync-notes.sh --evidence. Review, then write the note.\n'
    } > "$f"
    case "$note" in
      ASSETS-IMAGES)
        python3 "$HERE/scan-unused-assets.py" "$SRC" 2>/dev/null \
          | sed 's/^/unused-candidate\t/' >> "$f" || true ;;
      API-MAP)
        # This scanner reports JSON, and a `"router": null` means it recognised no router shape in
        # this repo — a real result, not an empty one. Prefixing JSON lines as if they were rows
        # produced nonsense candidates, so: keep the JSON as JSON, and when it found nothing, file
        # the handoff. That is the case where the script must be taught this repo's shape, and the
        # report carries what it looked for and what is actually here.
        raw="$EVID/API-MAP.json"
        python3 "$HERE/scan-api-map.py" "$SRC" > "$raw" 2>/dev/null || true
        declared="$(sed -n 's/.*"declared": *\([0-9]*\).*/\1/p' "$raw" | head -1)"
        shapes="$(grep -rl 'var path' --include='*.swift' "$SRC" 2>/dev/null | grep -c . || true)"
        printf 'scanner-output\t%s\n' "${raw#"$ROOT"/}" >> "$f"
        printf 'endpoints-found\t%s\n' "${declared:-0}" >> "$f"
        printf 'files-with-a-path-property\t%s\n' "$shapes" >> "$f"
        if [ "${declared:-0}" -eq 0 ] && [ "$shapes" -gt 0 ]; then
          "$HERE/ga-handoff.sh" Scripts/scan-api-map.py 1 \
            --cause "recognised no router shape, but $shapes file(s) here declare a path property" \
            --file "$raw" \
            --want "one router enum whose path property switches over its cases" \
            --got "$shapes file(s) with a path property — probably one enum per feature" \
            >/dev/null 2>&1 || true
          printf 'handoff\tfiled — the scanner needs this repo shape; see .genericarch/failures/\n' >> "$f"
        fi ;;
      NAVIGATION)
        grep -rn 'case ' --include='*.swift' "$SRC" 2>/dev/null \
          | grep -iE 'route|destination|screen' | sed 's/^/route-candidate\t/' | head -200 >> "$f" || true ;;
      FEATURES)
        find "$SRC" -name '*View.swift' -o -name '*Screen.swift' 2>/dev/null \
          | sed "s|$SRC/||; s/^/screen-candidate\t/" | LC_ALL=C sort >> "$f" || true ;;
      STYLE-GUIDE)
        grep -rhoE '(padding|cornerRadius|spacing)\(([0-9]+)\)' --include='*.swift' "$SRC" 2>/dev/null \
          | LC_ALL=C sort | uniq -c | LC_ALL=C sort -rn \
          | awk '{printf "repeated-value\t%s\t%s occurrences\n", $2, $1}' | head -60 >> "$f" || true ;;
      SCHEMES)
        find "$SRC" -name '*.xcconfig' -o -name '*.xcscheme' 2>/dev/null \
          | sed "s|$SRC/||; s/^/config-file\t/" | LC_ALL=C sort >> "$f" || true ;;
    esac
    printf '  %s→%s %-14s %s candidate(s)  %s%s%s\n' "$DIM" "$OFF" "$note" \
      "$(awk '!/^#/' "$f" | grep -c . || true)" "$DIM" "${why:0:52}" "$OFF"
  done
  printf '\n%s.claude/notes/.evidence/ — candidates, not rows. /sync-app-notes reviews these instead%s\n' "$DIM" "$OFF"
  printf '%sof re-running the scans, which is where the saving is.%s\n' "$DIM" "$OFF"
  exit 0
fi

# ── report / check / apply ─────────────────────────────────────────────────
printf '%s── Mechanical notes ───────────────────────────────────%s\n\n' "$BLD" "$OFF"
drift=0; applied=0; nomark=0
TMP="$(mktemp -t ga-sync-notes)"
trap 'rm -f "$TMP" "$TMP.cur"' EXIT INT TERM

unproven_for() { printf '%s\n' "$UNPROVEN" | awk -F: -v n="$1" '$1==n {sub(/^[^:]*:/, ""); print; exit}'; }

for n in $MECHANICAL $PARTIAL; do
  [ -n "$ONLY" ] && [ "$ONLY" != "$n" ] && continue
  f="$NOTES/$n.md"
  if [ ! -f "$f" ]; then
    printf '  %s·%s %-16s no such note here\n' "$DIM" "$OFF" "$n"; continue
  fi
  "gen_$n" > "$TMP" 2>/dev/null; rc=$?
  if [ "$rc" -eq 3 ]; then
    printf '  %s·%s %-16s this repo has none — nothing to sync\n' "$DIM" "$OFF" "$n"
    continue
  fi
  if [ "$rc" -ne 0 ]; then
    handoff "Scripts/sync-notes.sh (gen_$n)" "the $n generator failed on inputs that exist — a shape it does not know" "$f"
    continue
  fi
  gen_rows=$(awk '/^\|/ && $0 !~ /^\| *-+/ && NR > 2' "$TMP" | grep -c . || true)
  case " $PARTIAL " in
    *" $n "*)
      # Inside the managed block, so it is impossible to read the table without it.
      { printf '\n'; printf '> **Generated, and incomplete on purpose.** The %s row(s) above are parsed from the\n' "$gen_rows"
        printf '> tree. What this scan does **not** establish: %s.\n' "$(unproven_for "$n")"
        printf '> Candidates and method notes: `.claude/notes/.evidence/%s.tsv`.\n' "$n"
      } >> "$TMP" ;;
  esac
  if ! has_markers "$f"; then
    printf '  %s!%s %-16s %s row(s) ready — %sno markers yet: run --init-markers%s\n' \
      "$YEL" "$OFF" "$n" "$gen_rows" "$DIM" "$OFF"
    nomark=$((nomark + 1)); continue
  fi
  current_rows "$f" > "$TMP.cur"
  if cmp -s "$TMP" "$TMP.cur"; then
    printf '  %s✓%s %-16s %s row(s), in sync\n' "$GRN" "$OFF" "$n" "$gen_rows"
    continue
  fi
  cur_rows=$(grep -c '^|' "$TMP.cur" || echo 0)
  case "$MODE" in
    apply)
      replace_rows "$f" "$TMP"
      printf '  %s~%s %-16s rewritten: %s row(s) (was %s)\n' "$GRN" "$OFF" "$n" "$gen_rows" "$cur_rows"
      applied=$((applied + 1)) ;;
    *)
      printf '  %s~%s %-16s DRIFT: generated %s row(s), note has %s\n' "$YEL" "$OFF" "$n" "$gen_rows" "$cur_rows"
      drift=$((drift + 1)) ;;
  esac
done

echo
printf '%s── Needs judgement, not this script ───────────────────%s\n\n' "$BLD" "$OFF"
printf '  %sPartial notes above carry their own caveat line; these two are not generated at all:%s\n' "$DIM" "$OFF"
printf '%s\n' "$JUDGEMENT" | while IFS=: read -r note why; do
  [ -n "$note" ] || continue
  printf '  %s·%s %-14s %s%s%s\n' "$DIM" "$OFF" "$note" "$DIM" "$why" "$OFF"
done
printf '\n  %s--evidence gathers candidates for these, offline. /sync-app-notes writes the rows.%s\n' "$DIM" "$OFF"

echo
if [ "$fail_count" -gt 0 ]; then
  printf '%s%d generator(s) failed — handoff report(s) in .genericarch/failures/%s\n' "$RED" "$fail_count" "$OFF"
  printf 'Give the report to Claude. It does not need the script.\n'
  exit 1
fi
[ "$nomark" -gt 0 ] && { printf '%s%d note(s) have no managed-row markers — run: ./Scripts/sync-notes.sh --init-markers%s\n' "$YEL" "$nomark" "$OFF"; exit 3; }
case "$MODE" in
  apply) printf '%s%d note(s) rewritten. Nothing outside the markers was touched.%s\n' "$GRN" "$applied" "$OFF"
         printf '%sStamp the tree hash so a later check is one comparison: ./Scripts/notes-staleness.sh --stamp%s\n' "$DIM" "$OFF" ;;
  check) [ "$drift" -gt 0 ] && { printf '%s%d note(s) have drifted — run --apply%s\n' "$YEL" "$drift" "$OFF"; exit 1; }
         printf '%sEvery mechanical note is in sync.%s\n' "$GRN" "$OFF" ;;
  *)     [ "$drift" -gt 0 ] && printf '%s%d note(s) would change. --apply writes them, --check exits 1 for CI.%s\n' "$YEL" "$drift" "$OFF" \
                            || printf '%sEvery mechanical note is in sync.%s\n' "$GRN" "$OFF" ;;
esac
exit 0
